{/* TODO: Fill in missing images */ }
const foodWhitelist = [
    // https://www.dailymail.co.uk/femail/article-2788395/pass-protein-america-s-50-favorite-foods-revealed-steak-chicken-topping-list.html
    { "value": "Steak", "image": "https://openclipart.org/download/209621" },
    { "value": "Chicken", "image": "https://openclipart.org/download/21738" },
    { "value": "Pizza", "image": "https://openclipart.org/download/183841" },
    { "value": "Waffles", "image": "https://openclipart.org/download/209701" },
    { "value": "Beef", "image": "https://openclipart.org/download/175668" },
    { "value": "Mozzarella cheese", "image": "https://openclipart.org/download/293568" },
    { "value": "Bacon", "image": "https://openclipart.org/download/209517" },
    { "value": "Corned beef", "image": null },
    { "value": "Avocado", "image": "https://openclipart.org/download/321371" },
    { "value": "Pasta", "image": "https://openclipart.org/download/209691" },
    { "value": "Pineapple", "image": "https://openclipart.org/download/299198" },
    { "value": "Peanut Butter", "image": "https://openclipart.org/download/308866" },
    { "value": "Hamburgers", "image": "https://openclipart.org/download/280262" },
    { "value": "Sushi", "image": "https://openclipart.org/download/315493" },
    { "value": "Pancakes", "image": "https://openclipart.org/download/278684" },
    { "value": "Noodles", "image": "https://openclipart.org/download/209689" },
    { "value": "Chocolate", "image": "https://openclipart.org/download/176948" },
    { "value": "Blueberries", "image": "https://openclipart.org/download/31381" },
    { "value": "Salmon", "image": "https://openclipart.org/download/209537" },
    { "value": "Banana", "image": "https://openclipart.org/download/189457" },
    { "value": "Ice Cream", "image": "https://openclipart.org/download/320949" },
    { "value": "Ham", "image": "https://openclipart.org/download/303163" },
    { "value": "Oysters", "image": "https://openclipart.org/download/209638" },
    { "value": "Mashed potatoes", "image": null },
    { "value": "Soup", "image": "https://openclipart.org/download/302112" },
    { "value": "Asparagus", "image": "https://openclipart.org/download/227161" },
    { "value": "Sweet potato", "image": "https://openclipart.org/download/1028" },
    { "value": "Donuts", "image": "https://openclipart.org/download/248990" },
    { "value": "Turkey", "image": "https://openclipart.org/download/266395" },
    { "value": "Candy", "image": "https://openclipart.org/download/216664" },
    { "value": "Grapes", "image": "https://openclipart.org/download/293005" },
    { "value": "Popcorn", "image": "https://openclipart.org/download/295665" },
    { "value": "Cashew nuts", "image": "https://openclipart.org/download/20171" },
    { "value": "Eggs", "image": "https://openclipart.org/download/23490" },
    { "value": "Watermelon", "image": "https://openclipart.org/download/252309" },
    { "value": "Tuna", "image": "https://openclipart.org/download/259194" },
    { "value": "Cheddar cheese", "image": "https://openclipart.org/download/299704" },
    { "value": "Shrimp", "image": "https://openclipart.org/download/297145" },
    { "value": "Strawberries", "image": "https://openclipart.org/download/227154" },
    { "value": "Artichokes", "image": "https://openclipart.org/download/291385" },
    { "value": "Halibut", "image": "https://openclipart.org/download/323296" },
    { "value": "Almonds", "image": "https://openclipart.org/download/301039" },
    { "value": "Mango", "image": "https://openclipart.org/download/130285" },
    { "value": "Meatballs", "image": "https://openclipart.org/download/194411" },
    { "value": "Apples", "image": "https://openclipart.org/download/314470" },
    { "value": "Lamb", "image": "https://openclipart.org/download/281091" },
    { "value": "Sweetcorn", "image": "https://openclipart.org/download/248688" },
    { "value": "Mushrooms", "image": "https://openclipart.org/download/26150" },
    { "value": "Rice pudding", "image": null },

    // Custom Foods
    { "value": "Sandwich", "image": "https://openclipart.org/download/194414" },
    { "value": "Fries", "image": "https://openclipart.org/download/314326" },
    { "value": "Taco", "image": "https://openclipart.org/download/151201" },
    { "value": "Bubble Tea", "image": "https://openclipart.org/download/312584" },
    { "value": "Tea", "image": "https://openclipart.org/download/319996" },
    { "value": "Coffee", "image": "https://openclipart.org/download/21426" },
    { "value": "Salad", "image": "https://openclipart.org/download/297571" },
    { "value": "Ribs", "image": "https://openclipart.org/download/209513" },
    { "value": "Curry", "image": "https://openclipart.org/download/312338" },
    { "value": "Hot Dog", "image": "https://openclipart.org/download/303785" },
    { "value": "Lobster", "image": "https://openclipart.org/download/223269" },


    // Cuisines
    { "value": "Chinese Food", "image": "https://openclipart.org/download/306198" },
    { "value": "Mexican Food", "image": "https://openclipart.org/download/314182" },
    { "value": "Indian Food", "image": "https://openclipart.org/download/221173" },
    { "value": "Italian Food", "image": "https://openclipart.org/download/171442" },
    { "value": "French Food", "image": "https://openclipart.org/download/314183" },
    { "value": "American Food", "image": "https://openclipart.org/download/303785" },
    { "value": "Fast Food", "image": "https://openclipart.org/download/306467" },
    { "value": "Seafood", "image": "https://openclipart.org/download/223269" },
    { "value": "Spicy Food", "image": "https://openclipart.org/download/230162" },
    { "value": "Vegetarian", "image": "https://openclipart.org/download/320586" },
    { "value": "Gluten Free", "image": "https://openclipart.org/download/203480" },
];

export default foodWhitelist;