const foodWhitelist = [
    // https://www.dailymail.co.uk/femail/article-2788395/pass-protein-america-s-50-favorite-foods-revealed-steak-chicken-topping-list.html
    { "value": "Steak", "image": null },
    { "value": "Chicken", "image": null },
    { "value": "Pizza", "image": null },
    { "value": "Waffles", "image": null },
    { "value": "Beef", "image": null },
    { "value": "Mozzarella cheese", "image": null },
    { "value": "Bacon", "image": null },
    { "value": "Corned beef", "image": null },
    { "value": "Avocado", "image": null },
    { "value": "Pasta", "image": null },
    { "value": "Pineapple", "image": null },
    { "value": "Peanut Butter", "image": null },
    { "value": "Hamburgers", "image": null },
    { "value": "Sushi", "image": null },
    { "value": "Pancakes", "image": null },
    { "value": "Noodles", "image": null },
    { "value": "Chocolate", "image": null },
    { "value": "Blueberries", "image": null },
    { "value": "Salmon", "image": null },
    { "value": "Banana", "image": null },
    { "value": "Ice Cream", "image": null },
    { "value": "Ham", "image": null },
    { "value": "Oysters", "image": null },
    { "value": "Mashed potatoes", "image": null },
    { "value": "Soup", "image": null },
    { "value": "Asparagus", "image": null },
    { "value": "Sweet potato", "image": null },
    { "value": "Donuts", "image": null },
    { "value": "Turkey", "image": null },
    { "value": "Candy", "image": null },
    { "value": "Grapes", "image": null },
    { "value": "Popcorn", "image": null },
    { "value": "Cashew nuts", "image": null },
    { "value": "Eggs", "image": null },
    { "value": "Watermelon", "image": null },
    { "value": "Tuna", "image": null },
    { "value": "Cheddar cheese", "image": null },
    { "value": "Prawns", "image": null },
    { "value": "Strawberries", "image": null },
    { "value": "Artichokes", "image": null },
    { "value": "Asparagus", "image": null },
    { "value": "Halibut", "image": null },
    { "value": "Almonds", "image": null },
    { "value": "Mango", "image": null },
    { "value": "Meatballs", "image": null },
    { "value": "Apples", "image": null },
    { "value": "Lamb", "image": null },
    { "value": "Sweetcorn", "image": null },
    { "value": "Mushrooms", "image": null },
    { "value": "Rice pudding", "image": null },

    // Custom Foods
    { "value": "Sandwich", "image": null },
    { "value": "Fries", "image": null },
    { "value": "Taco", "image": null },
    { "value": "Bubble Tea", "image": null },
    { "value": "Tea", "image": null },
    { "value": "Coffee", "image": null },
];

export default foodWhitelist;