export const CLICKHOME = 'CLICKHOME';
export const CLICKBROWSE = 'CLICKBROWSE';
export const CLICKPROMOTIONS = 'CLICKPROMOTIONS';
export const CLICKDINEIN = 'CLICKDINEIN';
export const CLICKSTORIES = 'CLICKSTORIES';
export const CLICKSIGNIN = 'CLICKSIGNIN';